# Generated by Django 4.1.3 on 2023-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ELDER', 'Elder'), ('ELDER_RELATED', 'Elder_related'), ('SOCIAL_WORKER', 'Social_worker')], default='ADMIN', max_length=50, verbose_name='Type'),
        ),
    ]
