# Generated by Django 4.1.7 on 2023-03-21 15:26

from django.conf import settings
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderrecord',
            name='taggedElder',
            field=models.ManyToManyField(related_name='taggedElder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elderrecord',
            name='uploadedFile',
            field=models.FileField(default='', upload_to=home.models.media_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
    ]
