# Generated by Django 4.1.7 on 2023-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_card',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ELDER', 'Elder')], default='MANAGER', max_length=50, verbose_name='Type'),
        ),
    ]
