# Generated by Django 4.1.7 on 2023-03-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', '管理員'), ('ELDER', '長者')], default='ADMIN', max_length=50, verbose_name='Type'),
        ),
    ]
