# Generated by Django 4.1.7 on 2023-03-17 07:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_id_card_profile_user_remove_user_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=8, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='手機號碼格式輸入錯誤！', regex='^09\\d{8}$')], verbose_name='phone_num'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', '男'), ('FEMALE', '女'), ('ELSE', '其他')], default='MALE', max_length=10, verbose_name='sex'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
