# Generated by Django 4.1.7 on 2023-03-18 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_address_user_birthday_user_name_user_phone_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/<django.db.models.fields.related.OneToOneField>/')),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_tag', models.ManyToManyField(related_name='user_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
