# Generated by Django 4.1.7 on 2023-03-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_elderrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
