# Generated by Django 4.1.7 on 2023-03-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230319_0040'),
    ]

    operations = [
        
    ]
    
