# Generated by Django 4.1 on 2023-12-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_question_multimedia_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questionnaire',
        ),
    ]
