# Generated by Django 4.1 on 2023-12-28 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_answer_response_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response_file',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='home.questionnaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='response_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
