# Generated by Django 5.0 on 2024-01-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_answer_question_remove_answer_response_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='description',
        ),
    ]
