# Generated by Django 5.0 on 2024-01-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_questionnaire_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
