# Generated by Django 5.0 on 2024-01-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_user_user_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='url',
            new_name='edit_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_hash',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='reply_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
