# Generated by Django 5.0 on 2024-01-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_url_questionnaire_edit_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_hash',
            field=models.CharField(default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
