# Generated by Django 5.0 on 2024-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_user_user_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='response_url',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='response_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
