# Generated by Django 5.0 on 2024-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_answer_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
