# Generated by Django 5.0 on 2024-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_answer_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nano_guid',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='serial_number',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
    ]
