# Generated by Django 4.1.3 on 2023-03-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchdogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Elder',
        ),
        migrations.DeleteModel(
            name='Elder_related',
        ),
        migrations.DeleteModel(
            name='Social_worker',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
